platform :ios, '10.1'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MFCommonKit_Example' do
  pod 'MFCommonKit', :path => '../../MFCommonKit'
#  pod 'Alamofire', '~> 5.0'
  pod 'HandyJSON', '= 5.0.2-beta'
  pod 'SHFullscreenPopGestureSwift'
  pod 'MJRefresh'

  target 'MFCommonKit_Tests' do
    inherit! :search_paths
    
    
  end
  target 'MFSession' do
    inherit! :search_paths

    
  end
end
 
